import type { Metadata } from "next";
import { Inter, Roboto, Great_Vibes } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
})
const roboto = Roboto({
  subsets: ["latin"], 
  weight: ["400", "700"], // Specify weights you need (Regular and Bold)
  variable: "--font-roboto", 
});


const greatVibes = Great_Vibes({
  subsets: ["latin"], 
  weight: ["400"], // Great Vibes typically has only one weight (Regular)
  variable: "--font-great-vibes", 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link 
            rel="stylesheet" 
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" 
          />
      </head>
      <body className={`${inter.variable} ${roboto.variable} ${greatVibes.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
